- manifest.webapp
- package.json
- src/components/ContactsList/ContactRow.jsx
- src/components/ContactsList/ContactsHeader.jsx
- src/components/ContactsList/ContactsList.jsx
- src/components/ContactsList/index.js
- src/components/IntentApp.jsx
- src/targets/intents/App.jsx
- src/targets/intents/index.ejs
- src/targets/intents/index.jsx
- yarn.lock
With a query parameter (`?fakeintent`) in the url, you can see a button to pick a contact from the contacts list.
> feat: serve intents to pick a contact

- manifest.webapp
Voici une petite PR pour mettre à jour en autre le titre dans la cozy-bar.
Avant | Après
------|------
> feat: Change title on cozy bar 🎨

- src/components/IntentApp.jsx
- src/components/PickContacts.jsx
- src/locales/en.json
- src/styles/intent.styl
- add a cancel button
- add a global layout
- add a selection number
- add a header
In this PR I will:
I don't know if I will do the two last points, we'll see.
> feat: enhance pick-contact modal

- jest.config.js
- test/__mocks__/fileMock.js
- take into account `.json` and `.styl` files
- mock assets imports
- [mocks css modules](https://facebook.github.io/jest/docs/en/webpack.html#mocking-css-modules) (though i'm not sure we need that?)
- transforms `cozy-ui` modules
> chore: update jest config

- src/components/ContactCard/ContactIdentity.jsx
- src/styles/contactModal.styl
Avoids text overflows and some layout changes on mobile.
> fix: style adjustments for mobile and very long content

- src/components/ContactsApp.jsx
- src/styles/contacts.styl
c08c7ea (Enguerran, 17 seconds ago)
fix: delete is a dangerous action
57eaf36 (Enguerran, 69 minutes ago)
fix: button with icon is not centered
related to https://github.com/cozy/cozy-ui/issues/338
> fix: some UI improvements

- package.json
- src/assets/icons/plus.svg
- src/components/Buttons/ContactsIntentButton.jsx
- src/components/Buttons/OpenContactFormButton.jsx
- src/components/ContactCard/ContactCard.jsx
- src/components/ContactCard/ContactFieldForm.jsx
- src/components/ContactCard/ContactFields.jsx
- src/components/ContactCard/ContactForm.jsx
- src/components/ContactCard/ContactForm.spec.jsx
- src/components/ContactCard/__snapshots__/ContactForm.spec.jsx.snap
- src/components/ContactPropTypes.js
- src/components/ContactsApp.jsx
- src/components/ContactsList/ContactsHeader.jsx
- src/components/ContactsList/index.js
- src/components/Modals/ContactCardModal.jsx
- src/components/Modals/ContactFormModal.jsx
- src/helpers/contacts.js
- src/helpers/contacts.spec.js
- src/locales/en.json
- src/styles/contactForm.styl
- src/styles/contacts.styl
- src/styles/index.styl
- yarn.lock
This Pull Request aims to add:
- a menu in the contacts list
- a button in the menu
- a modale and a form for contact creation
This modale is sliced as below:
As explained here :trello: https://trello.com/c/bZaQ18TS/716-3-cr%C3%A9er-un-nouveau-contact-simple we will use https://github.com/final-form/final-form to manage the creation form but tests may not depend on it to decouple the implementation and the behavior and rendering.
> feat: add contact

- package.json
- src/components/ContactCard/ContactIdentity.jsx
- src/components/ContactCard/__snapshots__/ContactCard.spec.jsx.snap
- src/components/ContactsList/ContactRow.jsx
- src/components/Modals/ContactCardModal.jsx
- src/components/Modals/ContactFormModal.jsx
- src/helpers/contacts.js
- src/styles/contactForm.styl
- yarn.lock
Upgrades to the lastest version of cozy-ui and fixes a couple of things that broke along the way.
> upgrade cozy-ui

- src/locales/en.json
> fix: add missing translations

- src/components/ContactsList/index.js
[Emails shouldn't be mandatory](https://github.com/cozy/cozy-doctypes/pull/31).
> fix: display contacts without email

- src/components/ContactCard/ContactGroups.jsx
- src/components/ContactCard/__snapshots__/ContactCard.spec.jsx.snap
- src/components/ContactsApp.jsx
Reverts 41e0567d5b2b83f5eece64f8d39d63ca6eb8357b
> revert: make app writable again

- src/components/ContactsList/ContactsList.jsx
- src/components/ContactsList/index.js
- src/components/ContactsList/index.spec.js
> feat: sort contact by familyName

- src/components/Buttons/OpenContactFormButton.jsx
- src/components/ContactCard/ContactForm.jsx
- src/components/ContactCard/__snapshots__/ContactForm.spec.jsx.snap
- src/components/ContactsApp.jsx
- enable contact creation
- added a source marker
> feat: enable contact creation + cozy source

- package.json
- src/components/ContactCard/__snapshots__/ContactCard.spec.jsx.snap
- src/components/ContactCard/__snapshots__/ContactForm.spec.jsx.snap
- src/components/ContactsList/ContactsEmptyList.jsx
- src/styles/contacts.styl
- yarn.lock
Using Empty Component from UI because of style breaking changes.
~~⚠️ Needs a UI update to pass tests~~
> feat: Use Empty Component

- src/components/ContactsList/ContactsList.jsx
- src/components/PickContacts.jsx
- src/targets/intents/index.jsx
We will let third-party app able to create a new contact.
For instance, nothing more to add as it is a work in progress.
> feat: add intent to create a contact

- manifest.webapp
- package.json
- yarn.lock
> Release 0.5.3

- .travis.yml
- package.json
- src/components/App.jsx
- src/components/ContactCard/__snapshots__/ContactCard.spec.jsx.snap
- src/components/ContactsApp.jsx
- src/styles/index.styl
- src/targets/browser/index.ejs
- yarn.lock
Made Contacts fully iPhone X compatible (AFAIK) and also used the new Layout component from UI.
~~⚠️ **Do not merge !!! Waiting for a new release of UI**~~
> feat: Use new Layout component with iPhoneX compatibility

- src/components/ContactImportationModal/index.jsx
- src/connections/allContacts.js
- src/importation/index.js
- src/importation/index.spec.js
- src/importation/vcard.js
- src/importation/vcard.spec.js
- src/locales/en.json
We check email address or phone number to check
if a contact already exists in the cozy-stack.
If we found a contact with same email or phone number
we merge data.
Note that we cannot send an unique server query to
search for contacts with differents properties as keys.
> feat: do not import contacts that already exist

- src/connections/allContacts.js
- src/connections/merge.spec.js
- src/helpers/findContact.js
- src/helpers/mergeContact.js
- src/helpers/mergeContact.spec.js
I added some tests to cover the merge strategies.
I don't know if we may use jest Snapshot or JS expected object.
As I wrote the merge code with TDD, I did not use Jest Snapshot.
> feat: Update vcard merge strategies

- manifest.webapp
- package.json
- fix: Reset input to fire onChange on Chromium
- fix: Prevent toolbar from shrinking
- fix: Error when creating a new contact if list is empty
- feat: Update vcard merge strategies
- feat: Remove fullname from schema
> chore: prepare release 0.6.1

- manifest.webapp
- package.json
- src/components/ContactsList/ContactsEmptyList.jsx
- src/components/Toolbar.jsx
This aims to be the release 0.6.2-beta1
> feat: Enable vcard import

- src/targets/browser/index.ejs
Used by the bar to display 'Cozy Contacts'
> Use app-name-prefix in .ejs template

- src/components/ContactsList/ContactsList.jsx
No need to have an include here ;)
> fix: Remove include

- src/components/ContactCard/ContactGroups.jsx
- src/components/ContactCard/ContactIdentity.spec.jsx
- src/components/ContactGroups/ContactGroupCreation.jsx
- src/components/ContactGroups/helpers/groups.js
- src/components/Modals/ContactCardModal.jsx
- src/locales/en.json
- src/styles/contactGroupCreation.styl
- Change string for no groups 
- Don't allow the creation of a seconde group with an already used name 
- Set modal in fullscreen on mobile 
- Align text to initial. No need to center it :o
> fix: PO feedbacks

- src/components/Buttons/ImportGoogleButton.jsx
It seems we need to `install` instead of `create`
> fix: INSTALL Intent

- src/components/ContactCard/ContactForm.jsx
- src/components/ContactCard/ContactGroups.jsx
- src/components/ContactCard/__snapshots__/ContactForm.spec.jsx.snap
Two small fixes related to group creations.
> Group fixes

- src/components/ContactCard/ContactFields.jsx
- refactor the code a bit
- make the cozy url contact field a link
- make the address a link to a map
> Improve contact view

- src/components/ContactsList/ContactsEmptyList.jsx
- src/styles/contacts.styl
- Fix the width of the container
> fix(EmptyView): Fix button width

- src/components/ContactsList/ContactsEmptyList.jsx
> fix(EmptyPage): Add padding bottom

- package.json
- src/components/ContactCard/ContactForm/ContactFormField.jsx
- src/components/ContactCard/ContactForm/__snapshots__/index.spec.jsx.snap
- src/components/ContactGroups/__snapshots__/ContactGroupManager.spec.jsx.snap
- yarn.lock
wait for https://github.com/cozy/cozy-ui/pull/818
> feat: Use new small cross and small plus icons

- src/components/ContactImportationModal/ContactImportationCard/index.jsx
> fix: ImportBar alignment

- babel-transformer.js
- jest.config.js
- package.json
- src/components/App.jsx
- src/styles/contacts.styl
- yarn.lock
> feat: Display Contacts in the CozyBar on smalscreen

- package.json
- src/components/ContactCard/ContactGroups.jsx
- src/components/ContactCard/ContactGroups.spec.jsx
- src/thunks/cleanTrashedGroups.js
- src/thunks/cleanTrashedGroups.spec.js
- yarn.lock
Needs https://github.com/cozy/cozy-client/pull/355 + a new cozy-client version.
> fix: Update cozy-client

- src/targets/browser/index.ejs
- src/targets/intents/index.ejs
This reverts commit 19b0a32eecf0d285cefa4f55bea5b999d55643ff.
> Revert "chore: :wrench: Use the favicon from the stack"

- src/components/Modals/ContactFormModal.jsx
- src/components/Modals/ContactFormModal.spec.jsx
- src/constants.js
- src/helpers/contacts.js
- src/helpers/contacts.spec.js
- src/targets/browser/index.jsx
> feat: Use cozy-client for automatic metadata

- src/components/Modals/ContactCardModal.jsx
- src/helpers/flags.js
Remove `edit-contact` flag, always display Edit button
> feat: Remove flag for Edit contact feature

- src/components/Modals/ContactFormModal.jsx
I don't like when eslint complains.
> fix: Remove eslint warning about console.warn

- manifest.webapp
- package.json
> chore: Upgrade to 0.8.0

- src/components/ContactCard/ContactFieldInput.jsx
- src/components/ContactCard/ContactForm/ContactFormField.jsx
- src/components/ContactCard/ContactForm/__snapshots__/index.spec.jsx.snap
- src/components/ContactCard/ContactForm/index.jsx
- src/components/ContactCard/ContactForm/index.spec.jsx
- src/components/Form/HasValueCondition.jsx
- src/components/Form/HasValueCondition.spec.jsx
- src/components/Form/__snapshots__/HasValueCondition.spec.jsx.snap
- src/components/Form/__snapshots__/fields.spec.jsx.snap
- src/components/Form/fields.jsx
- src/components/Form/fields.spec.jsx
- src/locales/en.json
- Change label placeholder to label (TODO: change it in French translations)
- Field arrays: Replace add button on row by a unique button under all rows
- Display label field if it has a value (see https://codesandbox.io/s/lm4p3m92q for an example + doc about `Condition` field in react-final-form)
- If a field that has a label has been focused, its label does not disappear anymore
- use cozy-ui fields
> Contact form improvements

- src/components/Components/GroupItem.jsx
- src/components/ContactCard/ContactCard.jsx
- src/components/ContactCard/ContactCard.spec.jsx
- src/components/ContactCard/ContactGroups.jsx
- src/components/ContactCard/__snapshots__/ContactCard.spec.jsx.snap
- src/components/ContactGroups/ContactGroupList.jsx
- src/components/Modals/ContactCardModal.jsx
This is the first try to use only one query to get `allGroups`.
First time ever I use `queryConnect` 💪
> fix: Use only one Query to get allGroups

- src/components/ContactCard/ContactIdentity.jsx
- src/components/ContactCard/__snapshots__/ContactCard.spec.jsx.snap
Center contact's name only on mobile
> fix: Don't center contact's name on desktop

- package.json
- src/targets/browser/index.jsx
- yarn.lock
Make the bar use our own `CozyClient` (fixes an issue that appeared since cozy-bar was upgraded to 6.25.4)
> Pass our own cozy client to bar

- package.json
- src/components/ContactCard/ContactForm/ContactFormField.jsx
- src/components/ContactCard/ContactForm/__snapshots__/index.spec.jsx.snap
- src/components/ContactGroups/__snapshots__/ContactGroupManager.spec.jsx.snap
- src/styles/contactForm.styl
- yarn.lock
Adding a wrapper for a line so the delete button of this line is properly positionned.
~~⚠️ Goes along with https://github.com/cozy/cozy-ui/pull/979 so wait until this is merged and UI updated in this PR to merge.~~
> fix: Edit form's delete line button's position

- package.json
- src/components/ContactCard/ContactForm/__snapshots__/index.spec.jsx.snap
- src/components/ContactGroups/__snapshots__/ContactGroupManager.spec.jsx.snap
- src/components/Modals/ContactCardMenu.jsx
- yarn.lock
- Update cozy-client
- Update cozy-bar
- Update cozy-ui
> feat: Upgrade libs

- src/components/ContactsList/ContactRow.jsx
- src/components/ContactsList/ContactRow.spec.js
- src/components/ContactsList/Contacts/ContactCozy.jsx
- src/components/ContactsList/Contacts/ContactEmail.jsx
- src/components/ContactsList/Contacts/ContactIdentity.jsx
- src/components/ContactsList/Contacts/ContactName.jsx
- src/components/ContactsList/Contacts/ContactPhone.jsx
- src/components/ContactsList/__snapshots__/ContactRow.spec.js.snap
- src/components/ContactsList/__snapshots__/ContactsListDataLoader.spec.jsx.snap
- src/helpers/contacts.js
- src/styles/contacts.styl
- Add the cozyURL column 
- Change the order : email / phone / cozyURL 
- Hide the "me" flag 
Tech: 
- Each component has its own file
> Feat display cozy url

- src/components/Components/GroupItem.jsx
- src/components/ContactCard/__snapshots__/ContactCard.spec.jsx.snap
- src/components/ContactGroups/__snapshots__/ContactGroupList.spec.jsx.snap
> fix: Give more space to group name

- manifest.webapp
- package.json
> chore: Bump version to 0.8.6

- package.json
Same as in banks, yarn fixtures to load app fixtures
> chore: Add fixture script command

- manifest.webapp
- package.json
Changement de version pour la 0.8.9
> chore: Change to version 0.8.9

- CONTRIBUTING.md
- README.md
Remise des descriptions d'utilisation de Transifex dans les readme/contributing
> fix: Redo transifex contributing description

- package.json
- yarn.lock
Mise à jour de cozy-ui pour patcher les avatars
> chore: Update cozy-ui to fix circle avatar

- src/components/App.jsx
- Ajout temporaire d'un hack pour contourner le bug de la page blanche sur mobile.
- Le hack permet entre autre de facilité les tests sur mobile
- La solution viable est toujours programmée en backlog pour les prochaines semaines (vu avec @Crash-- )
> fix: Hack to avoid cozyBar error

- .github/auto-merge.yml
- CODEOWNERS
- package.json
- Add automerge config to support the "merge" label on PRs
- Add CODEOWNERS file to have reviewers automatically assigned
These two commits were part of the PR to update cozy-scripts
to version 4 but since this PR takes a little time to be debugged,
I extracted them.
> Automerge + CODEOWNERS

- src/components/App.jsx
- src/components/ContactGroups/ContactGroupManager.jsx
- src/components/ContactGroups/__snapshots__/ContactGroupManager.spec.jsx.snap
- src/components/ContactsList/ContactRow.jsx
We should not use the non transpiled version of cozy-ui
> fix: Use transpiled version of UI

- .gitignore
- manifest.webapp
- package.json
- src/components/ContactCard/ContactForm/formValuesToContact.js
- src/helpers/contacts.js
- src/helpers/contacts.spec.js
- src/helpers/doctypes.js
- src/helpers/fetches.js
- src/helpers/fetches.spec.js
- src/locales/en.json
- src/locales/es.json
- src/locales/fr.json
- src/targets/browser/index.jsx
- src/targets/services/keepIndexFullNameAndDisplayNameUpToDate.js
- yarn.lock
Ajout d'un service pour mettre à jour et maintenir les attributs fullname, displayName et Indexes des contacts.
Le service est lancé à la création/édition d'un contact, et met à jour si nécessaire les contacts qui ont été modifiés plus récemment que la dernière date d'exécution du service.
> feat: Add service to keep and update contacts attributes fullname, displayName, Indexes

- fixtures/contacts.json
- fixtures/massiveContacts.json
- package.json
- Add some flexibility with fixtures : we can now inject more than 2000 contacts in one shot and contacts without name
> Add fixtures to get contacts without names and thousands contacts

- src/components/Modals/ContactFormModal.jsx
- src/components/Modals/__snapshots__/ContactFormModal.spec.jsx.snap
Add a little spinner in contact form submit button
> fix: Add a spinner on contact form submit button

- src/components/App.jsx
> fix: Add cleanTrashedGroups in App useEffect dependecies

- package.json
- yarn.lock
- cozy-scripts fixes the problem with flaky builds
- cozy-bar updates removes a lot of dependencies
> Updtes cozy-scripts and bar

- CODEOWNERS
Use team in github to review PR
> chore: Change codeowners to have a team

- src/components/Components/ImportDropdown.jsx
- src/components/Components/StoreButton.jsx
- src/components/ContactImportationModal/ContactImportationCard/ImportationInput.jsx
- src/components/ContactsList/ContactsEmptyList.jsx
- src/components/ContactsList/StoreButton.jsx
- src/components/Toolbar.jsx
- src/helpers/store.js
- src/helpers/store.spec.js
- src/locales/en.json
- src/locales/es.json
- src/locales/fr.json
- yarn.lock
- extract from StoreButton and use function to get store url
- add dropdown button and action menu to import contacts from vcard or store
> feat: Add import action menu

- src/components/App.jsx
- src/components/ContentResult.jsx
- src/components/ContentResult.spec.jsx
- src/components/ContentWrapper.jsx
- src/components/Hooks/useService.jsx
- App no longer launch the service => moved in a hook
- Fix service to be relaunch after re-render
Branch created from https://github.com/cozy/cozy-contacts/pull/697
> Extract service logic from App

- manifest.webapp
- package.json
Change version from 0.8.11 to 0.9.0 : Contacts is no longer in Alpha
> fix: Change version to 0.9.0

- manifest.webapp
- package.json
> fix: Bump version to 0.9.1

- src/components/Modals/ConfirmDeleteModal.jsx
- src/components/Modals/ContactCardModal.jsx
- src/components/Modals/ContactCardModal.spec.jsx
- src/components/Modals/ContactInfo.jsx
- src/components/Modals/DumbContactCardModal.jsx
- src/components/Modals/DumbContactCardModal.spec.jsx
nothing changed, just refactoring
> refactor: Split ContactCardModal in different components

- manifest.webapp
- package.json
> chore: bump version to 0.9.2

- package.json
- src/components/App.jsx
- src/components/ContentWrapper.jsx
- src/components/Hooks/useService.jsx
- src/helpers/client.js
- src/targets/browser/index.jsx
- src/targets/browser/setupAppContext.jsx
- Use module.hot
- cozyClient init refactoring
- cozyBar hack removed
> Add hot reload

- src/components/Hooks/useService.jsx
- src/helpers/fetches.js
Add also better error messages when the normalized service cannot be fetched.
Without this PR, the contacts were not loaded in a local setup.
> fix: `hasBeenLaunched` should not be falsy in `useService`

- manifest.webapp
- package.json
> fix: BumpVersion to 0.9.3

- package.json
- src/components/ContactCard/ContactForm/formValuesToContact.spec.js
- src/helpers/contacts.js
- yarn.lock
- cozy-client update
- fixes and tests
> fix: DisplayName, fullname and defaultSortIndex on contact edition

- src/components/App.jsx
- src/components/ContactImportationModal/index.jsx
- src/components/ContactsList/ContactRow.jsx
- src/components/GroupsSelect/GroupsSelect.jsx
- src/components/GroupsSelect/GroupsSelect.spec.jsx
- src/components/Intents/CreateContact.jsx
- src/components/Modals/ContactCardModal.jsx
- src/components/Modals/ContactFormModal.jsx
- src/components/Modals/ContactFormModal.spec.jsx
- src/components/layout/ContactsSelectionBar.jsx
- src/connections/allContacts.js
- src/connections/allContacts.spec.js
- src/connections/allGroups.js
- refactor withGroupsMutations
- refactor withContactsMutations
> refactor: Remove withMutations

- src/components/ContentResult.jsx
- src/components/ContentResult.spec.jsx
- src/components/GroupsSelect/GroupsSelect.jsx
We can now decide to close the menu on select
> fix: Closing the groupSelect menu on select is now possible

- src/components/Common/ImportDropdown.jsx
- src/components/ContactsList/ContactsEmptyList.jsx
- src/components/ContentResult.jsx
- src/components/ContentRework.jsx
- src/components/Form/FieldInput.jsx
- src/components/Header.jsx
- src/components/Intents/IntentHandler.jsx
- src/components/Modals/ConfirmDeleteModal.jsx
- src/components/Modals/ContactCardModal.jsx
- src/components/Modals/ContactFormModal.jsx
- src/components/Modals/ContactInfo.jsx
- src/components/Toolbar.jsx
- src/components/layout/ContactsSelectionBar.jsx
- src/importation/report.js
- src/locales/en.json
- src/locales/es.json
- src/locales/fr.json
- refactor of contacts empty list
- remove useless hasConnector condition
- add new title
> Change title on contacts empty list if filtering

- src/components/ContentResult.spec.jsx
- src/helpers/groups.js
- src/locales/en.json
- src/locales/es.json
- src/locales/fr.json
Change "all contacts" to "all groups" in group selection
> fix: Change all-contacts to all-groups

- package.json
- src/components/ContactsList/__snapshots__/ContactRow.spec.js.snap
- yarn.lock
update cozy-scripts, cozy-client and cozy-ui, see commits messages
> Updates packages

- package.json
- yarn.lock
and fix partial index query result
> feat: Update cozy-client to 16.0.2

- manifest.webapp
- package.json
> chore: Bump to 0.9.6

- src/components/Common/ImportDropdown.jsx
- src/components/ContactCard/ContactForm/ContactFormField.jsx
- src/components/ContactImportationModal/ContactImportationCard/ImportationInput.jsx
- src/components/ContactsList/ContactsEmptyList.jsx
- src/components/GroupsSelect/GroupCreation.jsx
- src/components/GroupsSelect/SelectBox/Control.jsx
- src/components/Intents/IntentHandler.jsx
- src/components/Intents/PickContacts.jsx
- src/components/Modals/ContactInfoTitle.jsx
- src/components/Search/SearchInput.jsx
- src/components/Toolbar.jsx
> refactor: Use SVGr icons

- src/components/App.jsx
- src/components/ContactCard/ContactAccounts.jsx
- src/components/ContactCard/__snapshots__/ContactAccounts.spec.jsx.snap
- src/components/Modals/__snapshots__/ContactInfoContent.spec.jsx.snap
- src/styles/contacts.styl
> refactor: Remove 'cozy-ui/Text' and use Typography instead

- jestHelpers/setup.js
- package.json
- yarn.lock
> Update cozy-ui and cozy-client

- src/components/App.jsx
- src/helpers/bar.js
- src/targets/browser/setupApp.jsx
Use cozy-client to get application name
> refactor: Add appName as prop in <App />

- src/helpers/fetches.js
> refactor: Replace client.get by Q().getById

- .travis.yml
> chore: Fix CI

- jsconfig.json
> chore: Add jsconfig.json for editor autocompletion

- manifest.webapp
- package.json
```
* Bump version from 1.3.0 to 1.4.0
```
> chore: Bump version from 1.3.0 to 1.4.0

- .tx/config
- CONTRIBUTING.md
- README.md
```
* Add transifex config v3
```
> chore: Add transifex config v3

- .travis.yml
```
* Send a notification to the Publication Mattermost chanel every time a new version of the application is published
```
> Chore: Send a notification to Mattermost when publishing

- .bundlemonrc
- .travis.yml
- package.json
- yarn.lock
```
* Replace bundlesize by bundlemon
```
> chore: Replace bundlesize by bundlemon

- src/components/Modals/ContactFormModal.jsx
- src/queries/queries.js
See cozy/cozy-client@c5b6022 for more details
> refactor: Best approach for a getById request

- src/helpers/contacts.js
```
* Contact (myself) info modal will no longer display unwanted attributes
```
> Contact (myself) info modal will no longer display unwanted attributes

- package.json
- src/targets/browser/setupApp.jsx
- yarn.lock
> feat: Add sentry

- package.json
- yarn.lock
```
* Upgrade cozy-client to not destroy indexes automatically
```
> fix: Upgrade cozy-client

- .travis.yml
> chore: Disable npm cache

- src/components/ContactsList/CategorizedList.jsx
- src/helpers/contactList.js
- src/helpers/contactList.spec.js
- src/helpers/contacts.js
- src/helpers/contacts.spec.js
- src/helpers/filterWithRemaining.js
- src/helpers/filterWithRemaining.spec.js
Performance tests were carried out on the parent function, the before/after results are identical (between 164-177ms with 2200 contacts)
```
* Show mySelf always at the top of the list
```
> feat: Show mySelf always at the top of the list

- src/components/ContactCard/ContactForm/index.jsx
- src/components/ContactCard/ContactForm/index.spec.jsx
- src/components/Modals/ContactFormModal.spec.jsx
- src/locales/en.json
- src/locales/fr.json
Here we want to require the completion of one of the fields listed.
```
* Make some fields mandatory for creation
```
> feat: Make some fields mandatory for creation

- src/components/ContactCard/ContactForm/ContactFormField.jsx
```
* Adjust size of contact form field delete button
```
> refactor: Adjust size of contact form field delete button

- package.json
- src/components/ContactCard/ContactForm/fieldsConfig.js
- src/components/Form/FieldInputSelect.jsx
- yarn.lock
```
* Use bottom drawer for select input on mobile
```
> feat: Use new Select button on mobile

- src/components/Form/CustomLabelDialog.jsx
```
* For the contact labels, check `home` for undefined label with defined type
```
> feat(Labels): Check `home` for undefined label with defined type

- src/components/Form/CustomLabelDialog.jsx
```
* Check `home` if no label
```
> feat(Labels): Check `home` if no label

- src/components/ContactCard/ContactForm/ContactFormField.jsx
- src/helpers/fields.js
```
* Form inputs wasn't removed when clicking delete icon if last value
```
> Form inputs wasn't removed when clicking delete icon if last value

- package.json
- src/components/ContactCard/ContactFieldInput.jsx
- src/components/ContactCard/ContactForm/ContactFormField.jsx
- src/components/Form/FieldInputSelect.jsx
- src/styles/contactForm.styl
- yarn.lock
Corrige le style des libellés dans le formulaire de contact si le libellé personnalisé est une longue chaîne de caractère sans espace.
```
* Better display support for long content in labels
```
> Better display support for long content in labels

- src/components/GroupsSelect/GroupsSelect.jsx
- src/components/Modals/ContactInfoTitle.jsx
```
* Group menu in contact is now theme responsive
* Group delete from group menu wasn't working
```
> Group menu in contact is now theme responsive

- package.json
- src/components/App.jsx
- src/helpers/doctypes.js
- yarn.lock
```
* Add realtime on io.cozy.settings
```
> feat: Upgrade cozy-ui and add realtime on io.cozy.settings

- .stylintrc
- src/components/Common/ImportDropdown.jsx
- src/components/ContentResult.jsx
- src/components/GroupsSelect/GroupsSelect.jsx
- src/components/Search/SearchInput.jsx
- src/components/Toolbar.jsx
- src/locales/en.json
- src/locales/fr.json
- src/styles/contacts.styl
```
* Adjust style the toolbar and wording buttons in it
```
> feat: Adjust style the toolbar and wording buttons in it

- package.json
- src/components/AppLayout.jsx
- src/components/AppProviders.jsx
- src/components/ContactImportationModal/index.jsx
- src/components/GroupsSelect/useGroupSelect.jsx
- src/components/Modals/ContactFormModal.jsx
- src/components/Modals/ContactInfoTitle.jsx
- src/components/Modals/GroupDeleteConfirmationModal.jsx
- src/connections/allGroups.js
- src/connections/allGroups.spec.js
- src/tests/Applike.jsx
- yarn.lock
```
* Replace deprecated Alerter
```
> Replace deprecated Alerter

- src/components/ContactCard/ContactFieldInput.jsx
- src/components/ContactCard/ContactForm/ContactFormField.jsx
- src/components/ContactCard/ContactForm/ContactFormFieldArrayItem.jsx
- src/components/ContactCard/ContactForm/contactToFormValues.js
- src/components/ContactCard/ContactForm/formValuesToContact.spec.js
- src/components/ContactCard/ContactForm/index.jsx
- src/helpers/fields.js
- src/helpers/testData.js
```
* Id on contact form fields wasn't unique
* Custom labels were lost when deleting a field in the contact form arrays
```
> Fix some id issue on form fields

- .travis.yml
Transition to node 20 has been done successfuly on our production servers.
```
*
*
* Remove node 16 from tests in CI
* Remove stages in CI
```
> Remove node 16 from tests and stages in CI

- app.config.js
- package.json
- yarn.lock
présent car en peerDep de cozy-ui, mais utile dans cozy-ui uniquement pour le Viewer, non utilisé dans cette app.
```
* Remove harvest from dep
```
> feat: Remove harvest from dep

- src/components/ContactCard/ContactFields/ContactField.jsx
- src/components/ContactCard/ContactFields/FieldByType.jsx
- src/components/ContactCard/ContactFields/FieldTypes/index.jsx
- src/components/ContactCard/ContactFields/helpers.js
- src/helpers/contacts.js
- src/helpers/contacts.spec.js
- src/helpers/doctypes.js
- src/helpers/testData.js
> feat: Add contact relations to ContactInfoModal

- package.json
- yarn.lock
Following https://github.com/cozy/cozy-contacts/pull/1024 for mobile search
> feat: Update cozy-bar

- jest.config.js
- package.json
- src/components/ContactsList/ContactsList.jsx
- src/components/ContactsList/VirtualizedList.jsx
- src/components/ContactsList/__snapshots__/ContactListItem.spec.js.snap
- src/locales/index.js
- yarn.lock
behind `contacts.virtualization.enabled` flag
> Add virtualized table
