cozy/cozy-contacts

- package.json
- yarn.lock
I did clean the repository created by create-cozy-app, but I forget some libraries:
- redux-logger
- redux-mock-store
As we don't use redux (yet), I removed it for now.
> chore: remove unused redux libraries

- package.json
- yarn.lock
I rebase 3 Renovate PR into one.
Is that the way to do so? IDK
Changes:
49272bd (Renovate Bot, 31 hours ago)
fix(deps): update dependency cozy-client-js to v0.6.2
123cea9 (Renovate Bot, 31 hours ago)
fix(deps): update dependency cozy-bar to v4.8.7
655e999 (Renovate Bot, 31 hours ago)
fix(deps): update dependency cozy-scripts to v0.4.5
> Renovate: update multi libs

- src/components/ContactCard/ContactCard.jsx
- src/components/ContactCard/ContactCard.spec.jsx
We had a contact with the following structure:
```
{
name: { gibenName: 'John' },
randomField: ''
}
```
This caused 2 problems:
- We displayed a field "other", that contained nothing (`''`)
- That field was displayed before any other field
I fixed the two problems and added tests for theses cases (plus a bonus third one that hadn't caused problems… yet)
> fix: unsupported field problems

- .travis.yml
- package.json
While writing tests, I found the linting before the tests quite annoying. The linter will complain about `console.log` statements and other not too important things, and refuse to run the tests until they are fixed.
I also don't think there's a lot of value in linting before testing. They are just 2 different things. What do you think?
> chore: don't lint before tests

- src/components/ContactsApp.jsx
Before
After
Thanks @ptbrowne for the tips
> fix: menu in ContactCard is right positioned

- src/styles/contactCard.styl
see https://github.com/cozy/cozy-ui/issues/337
before
after
> fix: closing button is covered by menu button

- src/components/ContactCard/ContactFieldForm.jsx
- src/components/ContactCard/ContactForm.jsx
- src/components/ContactCard/__snapshots__/ContactForm.spec.jsx.snap
- src/locales/en.json
Adds placeholders to inputs and their labels.
I'm not very happy with the naming [here](https://github.com/cozy/cozy-contacts/compare/master...y-lohse:placeholders?expand=1#diff-9b0be75ed3549475f6997ba1248459d1R148) (`label`, `withLabel`, `labelPlaceholder`) but I don't have a better idea. Suggestions are welcome!
> feat: add placeholders in contact form

- src/components/ContactCard/ContactForm.jsx
- src/components/ContactCard/ContactFormField.jsx
- src/components/ContactCard/__snapshots__/ContactForm.spec.jsx.snap
It starts to smell when we have to drill down the props like that, doesn't it ?
> fix: disallow creating a contact without name

- src/components/ContactsApp.jsx
- src/components/ContactsList/ContactsList.jsx
- src/components/ContactsList/index.js
- src/components/HOCs/withSelection.jsx
- src/components/HOCs/withSelection.spec.jsx
- src/components/Modals/ContactCardModal.jsx
- src/components/Modals/ContactFormModal.jsx
- src/components/PickContacts.jsx
- src/connections/allContacts.js
A few things to look at:
- Since the regular app and the intent app now both have a selection, [I abstracted the selection logic into a HOC](https://github.com/cozy/cozy-contacts/pull/72/files#diff-ed03cf51242639d21e6ad9d5ede5c077R1)
- We can now delete a contact in 2 places, the `ContactCardModal` and the `ContactApp`. This means we want to connect 2 components with `cozy-client`, [so I moved the `cozy-client` declarations to a separate file](https://github.com/cozy/cozy-contacts/pull/72/files#diff-4185df2a7462c2c13eff6aa810d3b42bR1). I could be further abstracted but there's no need for that right now.
- In order to delete a contact at the `ContactApp` level, we needed the full contact information, not just the `id`. So I [changed the …
> Delete multiple contacts 

- src/components/ContactCard/ContactForm.jsx
Right now this does nothing at all, but in the next version of cozy-ui, the type will be propagated and validating the form with the enter key will work 👍
> fix: make the cancel button not a submit button

- src/helpers/contacts.js
- src/helpers/contacts.spec.js
After adding cozy-client, the `_id` field is also exported as `id`, but we don't want it to appear either.
> fix: filter out id field

- package.json
- src/components/Buttons/ContactsIntentButton.jsx
- src/components/Buttons/OpenContactFormButton.jsx
- src/components/ContactCard/ContactCard.jsx
- src/components/ContactCard/ContactForm.jsx
- src/components/ContactCard/__snapshots__/ContactCard.spec.jsx.snap
- src/components/ContactCard/__snapshots__/ContactForm.spec.jsx.snap
- src/components/ContactsApp.jsx
- src/components/Modals/ContactCardModal.jsx
- src/components/Modals/ContactFormModal.jsx
- src/components/PickContacts.jsx
- src/styles/contactCard.styl
- src/styles/contacts.styl
- yarn.lock
I've migrated the buttons and stuff to the latest cozy-ui, but we have a problem with the way Modals work now.
So far, we have decided that `ContactCard` and `ContactForm` are simply the *content* of a modal, but they could just as well be rendered inside a standalone page. So they are totally decoupled from the Modal API.
This is good on paper, but a problem in practice.
With the new API, it is quite important that we start using the `ModalHeader` and `ModalFooter` components in order to get the proper styling and scrolling behavior.
So for example [here](https://github.com/cozy/cozy-contacts/blob/master/src/components/ContactCard/ContactCard.jsx#L27), we would have to extract the `header` part and move it to [here, maybe](https://github.com/cozy/cozy-contacts/blob/master/src/components/M …
> chore: migrate to latest cozy-ui

- src/components/ContactGroups/ContactGroupManager.jsx
- prevent the tab key from selecting values
- capture the "escape" key propagation when the component has focus so the modal doesn't get closed
> fix: keyboard interactions on group manager

- package.json
This dep was added by mistake, it's actually provided by cozy-ui. The lockfile doesn't change since, well, the package is still there.
> chore: remove react-select dependency

- package.json
- src/components/ContactCard/__snapshots__/ContactCard.spec.jsx.snap
- src/components/ContactsApp.jsx
- src/components/Modals/ContactCardModal.jsx
- src/locales/en.json
- yarn.lock
The `ModalCard` is now a class with a state, to decide whether the confirmation modal is open or not. And after the deletion, we show an alert message. The changes are pretty straightforward!
Just waiting on the cozy-ui release.
> Confirmation modal before deleting a contact

- src/components/ContactImportationModal/ContactImportationCard/ContactImportationFile.jsx
- src/components/ContactsList/ContactsEmptyList.jsx
- src/importation/__fixtures__/datapoints.vcf
- src/importation/vcard.spec.js
The feature is still disabled by default, but can now be enabled with a query parameter: `enablevcardimport`: http://contacts-dev.cozy.tools:8080/?enablevcardimport
_note: Because react-router is used, the query parameters must be located just after the TLD: http://contacts-dev.cozy.tools:8080/?enablevcardimport#/folder_
This PR tries to fix or expose some feature:
- UI: Center the icon in the button (cf. https://github.com/cozy/cozy-ui/issues/554) https://github.com/cozy/cozy-contacts/pull/206/commits/690c17b56db0fb605dd224b684f1799e3ff09f69
- feat: Enable the feature with url query parameter enablevcardimport https://github.com/cozy/cozy-contacts/pull/206/commits/63fe72bf26609f9f2673ffae19ae60d5f8575295
- test: Check import of label datapoints that checks if labels in `*.vcf` are …
> feat: Import vcard

- src/components/App.jsx
Following up on #232 , but I didn't want to force push on @enguerran 's `master`.
> fix: Unfreeze the application when selecting a contact

- src/styles/contacts.styl
On small-ish screens, the toolbar would shrink and the list goes on top of the toolbar. This prevents the bar from shrinking below it's natural height.
> fix: Prevent toolbar from shrinking

- src/components/ContactsList/ContactsList.jsx
(Spotted during a candidate interview.)
If in the future we do not pass a sorted contact list, using lastLetter could introduce side effects by overrinding existing accumulator index.
Also, the same initialization can be done with a short-circuit evaluation.
> Avoid using lastLetter in reduce() for categorized contacts list

- README.md
ACH was mentionned without providing where to find it.
> Add ACH link

- renovate.json
We now have a shareable config for renovate — this repo is volunteering to be the test dummy.
> chore: Use cozy-app renovate config

- src/components/App.jsx
If we launch the app without importing data, when we create our first contact, we had 2 errors
> fix: Error when creating a new contact if contacts list is emty

- src/components/ContactCard/ContactIdentity.spec.jsx
- src/helpers/contacts.js
If contact didn't have a `name` then the app crashed.
> fix: Don't crash if contact doesn't have some info

- src/components/App.jsx
- src/components/ContactGroups/ContactGroupManager.jsx
- src/helpers/flags.js
We now have access to `cozy-flags` in `dev` mode. 
To test new feature in production, we can pass `?flags` in the url, to display the `FlagSwitcher`
We need to list our flags at the launch of the App if we want to be able to display all our flags. If we don't do that, flags will be only displayed when acceded 
I really don't like the UI :(
> feat: Add flags feature

- package.json
Our tests were running using preact instead of react. Usually not a big problem, but now that [`preact-portal`](https://github.com/cozy/cozy-ui/pull/723) is a peer dependency [it was causing errors](https://travis-ci.org/cozy/cozy-contacts/jobs/461227033#L2106).
> chore: Explicitly use react in tests

- package.json
- src/components/ContactCard/ContactGroups.jsx
- src/thunks/cleanTrashedGroups.js
- src/thunks/cleanTrashedGroups.spec.js
- yarn.lock
The groups where not deleted in the right field, which was causing problems.
There's still the underlying question of why groups seem to get saved in the `relationships` AND `groups` property, which I haven't investigated yet.
> Properly delete contact groups

- src/styles/contactCard.styl
The `elipsis` utility class was taking over these styles.
> fix: More specific styles for group names

- .travis.yml
- package.json
I don't like getting yelled at because there's an extra whit space while writing tests. If I want to lint *and* test, I can do it explicitly, so I'd rather have these 2 tasks be separate.
> chore: Don't lint on pretest

- README.md
`yarn start` is better than `yarn stack:docker` for newbies because
the former deactivates the Content Security Policy (CSP).
> docs: Fix README so it references `yarn start`

- src/components/App.jsx
We've to be careful. When we develop, the bar is served from our node_modules and it's already imported when we init the app. 
When builded for production, bar is served by the stack and is not ready during this phase. We have to wait for the render
> fix: Get bar during render

- src/helpers/contacts.js
The UI is broken if we leave `cozyMetadata` in fields in `ContactCard`
> Feat: filter cozyMetadata from fields

- package.json
- src/components/App.jsx
- src/components/Modals/ContactFormModal.jsx
- src/connections/allContacts.js
- src/connections/allContacts.spec.js
- src/helpers/contacts.js
- src/helpers/doctypes.js
- src/targets/browser/index.jsx
- yarn.lock
Contacts without sources are deleted right away, those with sources get a `trashed` flag and are ignored in the UI.
Two things to note:
- We need to use `_id` in the query as well, because we can't run a query only a non existing field.
- We're not using the cozy-client relationships to detect sources and instead rely on the metadata. This is because the google konnector doesn't generate the relationship at the moment. We should update this code once it's done, although it will continue to work.
> feat: Flag contacts with sources as trashed

- manifest.webapp
- src/components/App.jsx
- src/components/ContactCard/ContactAccounts.jsx
- src/components/ContactCard/ContactAccounts.spec.jsx
- src/components/ContactCard/ContactCard.jsx
- src/components/ContactCard/ContactCard.spec.jsx
- src/components/ContactCard/__snapshots__/ContactAccounts.spec.jsx.snap
- src/locales/en.json
- src/styles/contactCard.styl
In the body of the contact card, renders the sources linked to the contact if any.
We could use `ContactFields` component for this but it would require adaptation because:
- icons and field values are computed from the field type
- fields icons are "forced" in grey
Also, it seems fair to have a distinction between fields and accounts.
What do you think about it?
> Display accounts linked to the contact in the contact card

- src/components/ContactCard/ContactForm/__snapshots__/index.spec.jsx.snap
- src/components/ContactCard/ContactForm/contactToFormValues.js
- src/components/ContactCard/ContactForm/contactToFormValues.spec.js
- src/components/ContactCard/ContactForm/formValuesToContact.js
- src/components/ContactCard/ContactForm/formValuesToContact.spec.js
- fix bug when name is `undefined` (contact created via sharing)
- fix a lot of bugs when user clears values in the edit form (note, company, cozy, phone, address, email fields were not working correctly)
> Fix edit contact form

- package.json
- src/helpers/contacts.spec.js
- yarn.lock
Use [mockdate](https://www.npmjs.com/package/mockdate) instead of our own functions to mock date
> refactor: Use mockdate package

- package.json
- src/helpers/doctypes.js
- src/targets/browser/index.jsx
- yarn.lock
Update `cozy-client` and change its initialization to create/update cozy metadata according to https://github.com/cozy/cozy-client/commit/bf6be9b9a9c2e10f9b2e0a3704ae1692e76f3f86
> feat: Update cozy-client to 6.9.0 (new cozy metadata creation/update)

- src/components/ContactCard/ContactCard.jsx
- src/components/ContactCard/ContactCard.spec.jsx
- src/components/ContactCard/__snapshots__/ContactCard.spec.jsx.snap
If `sourceAccount` is `null`, it means that the linked `io.cozy.accounts` has been deleted (the user disconnected the account or removed the google konnector)
See https://github.com/konnectors/cozy-konnector-google/pull/296 to see how we set `sourceAccount` to `null` on delete.
> Don't display disconnected contact accounts

- src/components/ContactCard/ContactCard.jsx
- src/components/Modals/ContactCardModal.jsx
- src/components/layout/ContactsSelectionBar.jsx
- src/helpers/contacts.js
- src/helpers/contacts.spec.js
- src/locales/en.json
Sorry, a bit light on the tests — but adding snapshots for the delete modal requires a lot more effort than what we wanted to give this task.
> feat: Better delete warning

- src/components/ContactCard/ContactForm/formValuesToContact.js
- src/components/ContactCard/ContactForm/formValuesToContact.spec.js
- src/components/ContactCard/ContactForm/index.jsx
If `metadata.google` is present in the contact, don't erase it when we edit the contact.
We need this to ensure we have an etag for contacts during sync (See: https://github.com/konnectors/cozy-konnector-google/pull/333 )
> fix: Don't erase metadata.google when the contact is edited

- src/components/ContactCard/ContactForm/__snapshots__/index.spec.jsx.snap
- src/components/ContactCard/ContactForm/formValuesToContact.js
- src/components/ContactCard/ContactForm/formValuesToContact.spec.js
If cozy url is empty, it should be an empty array, not an empty string in contact doctype.
> fix: cozy url is an array, not a string

- package.json
- scripts/20190429_migrateContacts.js
- scripts/20190429_migrateContacts.spec.js
- yarn.lock
See comment at the top of `migrateContacts.js` for what it does.
A few questions:
- I should probably rename `migrateContacts.js` but can't really find a good name. Maybe at least add a version `contactsMigration1.js`?
- I could add a test for `run`/`doMigrations` but I'm not sure that it worths it.
- it introduces a dependency to ACH. Maybe it should at least be a `devDependency`. @ptbrowne how do you handle this for external scripts?
> feat: Add migration script for contacts

- scripts/20190429_migrateContacts.js
To avoid unnecessary queries on cozies that does not have contacts
> fix: Do the contacts accounts query only if we have contacts to migrate

- src/components/ContactGroups/ContactGroupManager.jsx
ATM we can't delete a created group since the icon is not there anymore
> fix: Use the right icon

- jest.config.js
- package.json
- yarn.lock
Added `browser: true` to force jest to use  `browser` entry point (needed for new version of cozyclient)
> feat: Upgrade cozy-client

- package.json
- yarn.lock
Since Chrome 82 or 83, they changed the default alignment for buttons.
so we need to force it now.
See the fix in UI : https://github.com/cozy/cozy-ui/pull/1399
> fix: Upgrade Cozy-UI to fix visual regressions with Chrome

- src/components/App.jsx
- src/components/ContentWrapper.jsx
- src/helpers/bar.js
- src/helpers/client.js
- src/store/configureStore.js
- src/targets/browser/index.jsx
This PR is a part [2] of multiple PR about the new sort logic in the application. Tests will maybe failed and probably don't after merging previous PR and rebasing this one.
- Refactor App to use functional component / hooks
- (*) Extract the main query to new file
- Cleanup browser index (app init) and store configuration
(*) the Query is still not using hooks. It is the very first refactor, the hook will comes in an other PR
> refactor: App to functional component

- manifest.webapp
- package.json
- src/components/App.jsx
- src/components/ContactCard/ContactForm/formValuesToContact.spec.js
- src/components/ContentWrapper.jsx
- src/components/ContentWrapper.spec.jsx
- src/components/Hooks/fetchSortedContacts.js
- src/components/Hooks/useFetchContacts.js
- src/components/Hooks/useFlags.js
- src/helpers/contacts.js
- src/helpers/contacts.spec.js
- src/helpers/fetches.js
- src/helpers/fetches.spec.js
- src/helpers/queries.js
- src/targets/services/keepIndexFullNameAndDisplayNameUpToDate.js
- yarn.lock
If service `keepIndexFullNameAndDisplayNameUpToDate` was already launched we want to sort contacts in a specific way. So we have to test that first, then query contacts in a way or in an other.
- Check if service was launched
- Fetches and sort contacts in two differents ways
- Refactor of fetch function to get the service
> Use two differents queries depends if index service was launched

- README.md
- src/components/App.jsx
- src/helpers/fetches.js
- src/helpers/fetches.spec.js
- src/targets/services/keepIndexFullNameAndDisplayNameUpToDate.js
- Add some documentations for Fixtures and Services
- Fix bug "Invalid time value" when accessing current_state.last_success property of a trigger
When a service was never launched, current_state.last_success is undefined
> fix: Error Invalid time value for service keepIndexFullNameAndDisplayNameUpToDate

- src/components/ContactsList/ContactRow.jsx
- src/components/ContactsList/ContactRow.spec.js
- src/components/ContactsList/ContactsList.jsx
- src/components/ContactsList/__snapshots__/ContactRow.spec.js.snap
- Lines in the list are only re-rendered if there is a change of contact or breakpoints, which avoids re-rendering all lines when only one contact is changed.
- Remove useless `withModalContainer` (add props to show/hide modal) HOC on `ContactRow`
edit : will add some tests
> fix: Rerender ContactRow only on contact or breakpoints change

- src/components/Modals/ContactFormModal.jsx
At the time of the creation/editing of a contact, when a field was modified, during the validation of the form, the old data was re-displayed (because of re-rendering the component with old data)
> fix: ContactForm no longer show old contact after submit

- src/helpers/fetches.js
- src/helpers/fetches.spec.js
If the service was not installed, the list was not displayed and remained stuck on the spinner because of the function to retrieve the service that returned an error.
fix https://github.com/cozy/cozy-contacts/issues/682
> fix: List doesn't show up if service not installed

- src/helpers/queries.js
Exclude trashed contacts from the result of the query
> fix: Exclude trashed contact with no indexes

- README.md
Add a link to the service documentation and a note specifying a service must be installed to work
> docs: Add link to service documentation

- package.json
- src/components/ContactCard/ContactForm/formValuesToContact.spec.js
- src/components/ContactCard/ContactForm/index.spec.jsx
- src/components/ContactsList/ContactsList.jsx
- src/helpers/contactList.js
- src/helpers/contactList.spec.js
- src/helpers/contacts.js
- src/helpers/contacts.spec.js
- yarn.lock
Due to a change in cozy-client behavior https://github.com/cozy/cozy-client/pull/785, this is a simple consistency update.
- the value of the `Indexes` attribute is now a `null` rather than a `{}` when it should be empty.
- bonus : some cleans up
> fix: Sort contact after contact edition

- package.json
- src/helpers/contactList.js
- src/helpers/contactList.spec.js
- yarn.lock
Accents are removed when creating categories, to regroup contacts for example with "A" and "À" first letter
- Add test for null Indexes
According to https://medium.com/javascript-in-plain-english/not-so-obvious-removal-of-diacritics-in-javascript-explained-and-done-right-52f4aeb3c85 we chose to use `remove-accents`
> fix: Remove accents in categorization

- src/components/ContactCard/ContactForm/formValuesToContact.js
- src/components/ContactCard/ContactForm/formValuesToContact.spec.js
For imported contacts (vcard, google...), there may be other attributes than those supported by Cozy. When editing a contact, we must therefore keep these attributes instead of deleting them.
- we keep now prefix, suffix etc. of a contact name if present
- we keep now attributes present in the doctype, but not modified by the form
- we keep now other attributes not in the doctype
> fix: Additional name information and attributes are erased after editing a contact

- src/components/Modals/ContactCardModal.jsx
- src/helpers/queries.js
Use new singleDocData option in query definition to fetch contact by id
> refactor: Use singleDocData in queryContactById definition

- package.json
- yarn.lock
> chore: Remove react-hot-reload

- src/components/ContactCard/ContactForm/formValuesToContact.js
- src/components/ContactCard/ContactForm/formValuesToContact.spec.js
- src/components/ContactCard/ContactForm/index.jsx
- src/components/ContactCard/ContactForm/index.spec.jsx
- src/components/ContactCard/__snapshots__/ContactCard.spec.jsx.snap
- src/components/Modals/ContactFormModal.spec.jsx
- src/helpers/contacts.js
Emptying a field in the contact form now erase the relative contact data
- removing lodash merge that ignore undefined value (that's why it didn't erase the data, the 'undefined' was replaced by the old value.)
- homogenization (to empty string or array) of empty values after saving the form
- remove unformatted address (to formatted address) only if something change in the address
- refactor to use object as param
- add and fix tests
> fix: Emptied fields not erase in contact

- src/styles/contacts.styl
Prevent Topbar to be shrinked, specially in Safari
> fix: Safari topbar margin

- src/styles/contacts.styl
Topbar height is too high when only few contacts
will be merged as soon as CI will be green
> fix: Topbar height with just few contacts

- package.json
- src/components/ContactCard/ContactForm/index.spec.jsx
- src/components/ContactCard/__snapshots__/ContactAccounts.spec.jsx.snap
- src/components/ContactsList/Contacts/ContactIdentity.jsx
- src/components/ContactsList/__snapshots__/ContactListItem.spec.js.snap
- src/components/Modals/__snapshots__/ContactInfoContent.spec.jsx.snap
- src/targets/browser/index.jsx
- yarn.lock
> Update MUI v4

- package.json
- src/components/App.jsx
- src/targets/browser/setupApp.jsx
- src/targets/intents/index.jsx
- yarn.lock
When we arrive on the app, we can launch
the service to keep the index up to date.
By doing so, the service can upgrate the
contact's documents.
In that case, if we try to edit / delete a contact
that have been edited by the service, we will get
a 409 error since the app doesn't have the right
version of the document.
To fix this issue, let's connect to the realtime
to get the latest revision if a document is changed
by something.
> fix: Add realtime to contacts

- CHANGELOG.md
- package.json
- yarn.lock
This will fix a breaking change on react-native side
The NativeMessenger API changed
Thus, the WebviewMessenger has to be updated in order to communicate
> fix: Update cozy-intent

- package.json
- yarn.lock
In https://github.com/cozy/cozy-contacts/pull/893, I changed a _.where_ to a _.partialIndex_, and now when you click on the bin to delete a group, it disappears after 3s instead of 0s.
Adding a  _.where_ before the _.partialIndex_ fixes the problem and should not impact performance, but 
1. Do you know why ?
2. Is it a good fix ?
@paultranvan @Crash--
> fix: Groups took time to delete

- src/queries/queries.js
```
* Fix keepIndexFullNameAndDisplayNameUpToDate service execution
```
keepIndexFullNameAndDisplayNameUpToDate service use query located into queries.js. The service wans't able to find fetchPolicies which creates undefined exception that crash the service. To fix the problem, I follow convention used into the coachCO2 queries.js file
> fix(queries.js): use fetchPolicies in function instead as a constant

- package.json
- yarn.lock
```
* Upgrade cozy-client from 34.1.3 to 34.3.0
```
This upgrade aims to have fetchPolicies export also for node.
> feat: Upgrade cozy-client to 34.3.0

- src/styles/contacts.styl
```
* Add inline padding to topbar on mobile
```
> fix: Add inline padding to topbar on mobile

- src/components/Common/ImportDropdown.jsx
- src/helpers/store.js
- src/helpers/store.spec.js
It replaces legacy window.location and also handles native app.
Though the redirection doesn't work in local dev, because going
from http to https. I don't know if we want to handle that?
```
* Replace import contact action with an Applinker for better multi-platform behaviour
```
> fix: use AppLinker in contact import

- manifest.webapp
- src/components/Modals/ContactFormModal.jsx
- src/helpers/contacts.js
- src/helpers/contacts.spec.js
- src/helpers/doctypes.js
- src/queries/queries.js
Cette PR ajoute la possibilité de remplir les champs du formulaire avec les données trouvées dans `io.cozy.identities`, à la condition que le contact n'ait pas d'adresse.
Ainsi pour cette première itération, nous évitons toutes incohérences dans les adresses.
```
* Add addresses from a connector to the contact, if not filled in
```
> Add identities to Contact

- src/components/ContactsList/ContactsEmptyList.jsx
- src/connections/allContacts.js
- src/styles/contacts.styl
```
* Style of empty group view on mobile (2f1577a)
* Error handling if there are no contacts in a deleted group (f87f62d)
```
> Error handling if there are no contacts in a deleted group

- src/helpers/contacts.js
- src/helpers/contacts.spec.js
We did a manual sort and put "me" first in contacts list if the service was never launched.
If the service has already been launched, we retrieve the contacts such as (because it is the query which does the asc sorting), but in this case we must also put "me" first.
> fix: Correct order of contacts

- src/components/GroupsSelect/GroupsSelect.jsx
- src/components/Modals/ContactInfoTitle.jsx
```
* On Safari, the SelectBox menu for group creation from a contact's info modal passes below the content of the modal.
The change in approach to handling menu closure when clicked outside the menu means we can remove the `z-index` forced on the `react-select` container that was causing the problem.
```
> fix: Creation group with Safari

- src/components/ContactCard/ContactForm/contactToFormValues.js
- src/components/ContactCard/ContactForm/contactToFormValues.spec.js
- src/components/ContactCard/ContactForm/fieldsConfig.js
- src/components/ContactCard/ContactForm/formValuesToContact.js
- src/components/ContactCard/ContactForm/formValuesToContact.spec.js
- src/components/ContactCard/ContactForm/index.spec.jsx
- src/helpers/contacts.js
- src/helpers/contacts.spec.js
- src/helpers/testData.js
- src/locales/de.json
- src/locales/en.json
- src/locales/es.json
- src/locales/fr.json
- src/locales/nl_NL.json
```
* Add additionalName, surname and region fields
* Change list order for address
```
> Add additionalName, surname and region fields

- src/components/Actions/trash.jsx
- src/components/Modals/ConfirmDeleteModal.jsx
- src/connections/allContacts.js
- src/connections/allContacts.spec.js
```
* Update cozy-client
* Use client.destroy from new cozy-client 
```
> Use client.destroy from new cozy-client

- package.json
- src/targets/services/keepIndexFullNameAndDisplayNameUpToDate.js
- yarn.lock
```
* Add cozy-logger and use it in keepIndexFullNameAndDisplayNameUpToDate service
* keepIndexFullNameAndDisplayNameUpToDate service: Avoid crashing when service fetched is undefined
* Add yarn script to drop fixtures
```
> Fix keepIndexFullNameAndDisplayNameUpToDate service

- manifest.webapp
- package.json
- src/helpers/autoDefineLabelsService.js
- src/helpers/autoDefineLabelsService.spec.js
- src/helpers/fetches.js
- src/helpers/fetches.spec.js
- src/targets/services/autoDefineLabels.js
- src/targets/services/keepIndexFullNameAndDisplayNameUpToDate.js
C'est un service qui assure que les champs address/cozy/phone/email aient bien un label s'ils ont un type
```
* Add autoDefineLabels service
```
> Add autoDefineLabels

- src/helpers/autoDefineLabelsService.js
- src/helpers/autoDefineLabelsService.spec.js
Si un contact a déjà utilisé la nouvelle feature de libellé, il ne faut pas que le service le modifie.
> fix(Services): AutoDefineLabel should not modify existing correct contact

- package.json
- src/components/ContactCard/ContactFields/helpers.js
- src/components/ContactCard/ContactForm/contactToFormValues.js
- yarn.lock
see https://github.com/cozy/cozy-client/pull/1469
```
* Can now deal with `[null]` value for address/phone/email/cozy
```
> feat: Can now deal with `[null]` value for address/phone/email/cozy

- package.json
- src/components/Form/FieldInputSelect.jsx
- yarn.lock
Lorsqu'on définit un libellé personnalisé sur une adresse/téléphone/email/cozy, le champ "personnalisé" était toujours présent. Maintenant il suffit de recliquer sur ledit champ personnalisé pour le modifier, et non plus sur le champ marqué "personnalisé".
```
* Remove custom input on form label options when already customized
```
> feat: Remove custom input on form label options when already customized

- src/components/ContactCard/ContactForm/ContactFormField.jsx
related contact wasn't removable
> fix: Show remove logic in contact form

- src/targets/browser/index.ejs
- src/targets/intents/index.ejs
Our custom theme CSS was not taken into account because cozy-ui CSS was inserted after.
```
* Custom theme colors were not taken into account
```
> fix: Move custom theme CSS at end of <head>

- src/helpers/search.js
We noticed that the current search is a bit too permissive and can return too many false-positive.
Thus, we reduce the fuzzy matching threshold to be more strict.
```
* Improve fuzzy search by being stricter
*
*
```
> feat: Stricter fuzzy matching

- .travis.yml
We will only take into account .nvmrc
> chore: Remove node_js in .travis.yml

- src/components/ContactCard/ContactForm/RelatedContactList.jsx
- src/components/ContactCard/ContactForm/helpers.js
- src/components/ContactCard/ContactForm/index.jsx
- src/components/ContactCard/ContactForm/index.spec.jsx
When we wanted to create a new contact from the linked contact addition,
the form component was rendered because the creation of the new contact triggers useQueries higher up the React tree.
This re-rendering caused the form to lose any changes it had already made, such as adding the new linked contact.
> fix: Creation of a contact when selecting a linked contact

- manifest.webapp
- src/helpers/cleanRelatedContactsService.js
- src/helpers/cleanRelatedService.spec.js
- src/targets/services/cleanRelatedContacts.js
When you delete a contact, this service deletes any relationships it may have had with other contacts.
> feat: Add cleanRelatedContacts service

- src/components/ContactCard/ContactForm/fieldsConfig.js
- src/components/Modals/ContactFormModal.jsx
- src/components/Modals/ContactFormModal.spec.jsx
- src/connections/allContacts.js
- src/connections/relatedRelationships.js
- src/connections/relatedRelationships.spec.js
- src/locales/en.json
- src/locales/fr.json
- src/types.js
Following on from the work started on this PR https://github.com/cozy/cozy-contacts/pull/985.
The aim is to synchronize relationship changes between the contacts concerned.
> feat: Synchronize relation between contacts

- package.json
- src/components/AppLayout.jsx
- src/components/ContactCard/ContactGroups/__snapshots__/ContactGroupList.spec.jsx.snap
- src/components/ContactCard/__snapshots__/ContactAccounts.spec.jsx.snap
- src/components/ContactsList/__snapshots__/ContactListItem.spec.js.snap
- src/components/Hooks/useIntentBackdrop.jsx
- src/components/Intents/IntentHandler.jsx
- src/components/Modals/__snapshots__/ContactInfoContent.spec.jsx.snap
- src/styles/intent.styl
- src/tests/Applike.jsx
- yarn.lock
the entire app can be used in an iframe, as in cozy-admin for example. In this case, when a modal opens, there's a backdrop behind it, but it's constrained to the iframe. To extend this backdrop to the entire app, the iframe sends a `requestBackdropOpen` command received by the parent, triggering the opening of a global backdrop.
relative to https://github.com/cozy/cozy-admin/pull/8
> Add hook to tell the parent to trigger backdrop
